name: nutriplus
description: "A new Flutter project."

publish_to: 'none' # Remove esta linha se você quiser publicar seu pacote

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.7.0 # Adicione a versão do firebase_core
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/logo.png 
    - assets/images/logo_bg.png
    - assets/images/profile_placeholder.png
