// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD37D_CK9a3ID-CZ5CIjw0OBMApbnICzSI',
    appId: '1:191006655550:web:91671b8eeccbd9b1ccfd6f',
    messagingSenderId: '191006655550',
    projectId: 'nutriplus-b5190',
    authDomain: 'nutriplus-b5190.firebaseapp.com',
    storageBucket: 'nutriplus-b5190.appspot.com',
    measurementId: 'G-4H155263XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzGVL0ZAAX4fsm9SrxCZkCgPm4g_zDmFk',
    appId: '1:191006655550:android:9306a3aa83183b6eccfd6f',
    messagingSenderId: '191006655550',
    projectId: 'nutriplus-b5190',
    storageBucket: 'nutriplus-b5190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRP30dieMQaTTFF-fR_2-Ho3lCdNdEamM',
    appId: '1:191006655550:ios:e3305b007279e1cdccfd6f',
    messagingSenderId: '191006655550',
    projectId: 'nutriplus-b5190',
    storageBucket: 'nutriplus-b5190.appspot.com',
    iosBundleId: 'com.example.nutriplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRP30dieMQaTTFF-fR_2-Ho3lCdNdEamM',
    appId: '1:191006655550:ios:e3305b007279e1cdccfd6f',
    messagingSenderId: '191006655550',
    projectId: 'nutriplus-b5190',
    storageBucket: 'nutriplus-b5190.appspot.com',
    iosBundleId: 'com.example.nutriplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD37D_CK9a3ID-CZ5CIjw0OBMApbnICzSI',
    appId: '1:191006655550:web:7492607124592edfccfd6f',
    messagingSenderId: '191006655550',
    projectId: 'nutriplus-b5190',
    authDomain: 'nutriplus-b5190.firebaseapp.com',
    storageBucket: 'nutriplus-b5190.appspot.com',
    measurementId: 'G-56SGE7RT82',
  );
}
